### ISSUE TITLE
rewrite the data loader from txt function

### ISSUE THREAD

**Issue by 00arun00** [robo-bootcamp/pyBotic#5]
Current load 3d map from txt is really bad need to fix that 

Features required:
- support for loading from different types of file formats 
- support .txt, JSON (if, else .... )

Return:
- boundary: iter6d  
- obstacles: dict(key:iter6d), 
- start: iter3d (default:None)
- goal:iter3d (default:None)

**Comment by 00arun00** [comment]
write it as a data loader form file function 

currently supporting only .txt, but with the option to easily extend and support JSON and other famous formats

**Comment by gunjanpatil** [comment]
to support now:
- [x] error out if lengths of members don't match
- [x] error out if non - member string or non pythonic comments are present
- [x] what to return if start and obstacles are not given?
- [x] raise error if boundary, goal is not given
- [x] warn for multiple obstacles of same values

for later:
- [ ] allow different/same names for obstacles
- [ ] also support pythonic comments
